import { Address } from 'set-protocol-utils';

// Generated by mnemonic "candy maple cake sugar pudding cream honey rich booboo crumble sweet treat"
export interface Account {
  address: Address;
  privateKey: string;
}
const NULL_ADDRESS = '0x0000000000000000000000000000000000000000';

const ACCOUNTS: Account[] = [
  {
    address: '0x5dee77e75a0f9e5272a02d67ce0bf9f3608355fe',
    privateKey: '0x859678781994101043ece30f4f1315a919dffee9b5e70f0ac6b8ab3e3fe05fe6',
  },
  {
    address: '0xa33da2e00bf12026a0aa1bdc6670d8667a95a8be',
    privateKey: '0x5dcc0555c4e981122cfc6c34b7275604feeaeeca52ac782f36619a99573bf2a0',
  },
  {
    address: '0xc22be120845b6565fbb3768c7df74bb47bda88bc',
    privateKey: '0x2e04b35cec26e658516ddb012d3171ee92ca339646fe824648d5582b13b5a829',
  },
  {
    address: '0x5f63dd526d53edf386ce0f05d1749c1cee2e307a',
    privateKey: '0x34fda23aa544c03a50846e625dbda3fcfe5c6081d35a226f66c33c4e24cd345a',
  },
  {
    address: '0x3d677e3280eed79076af4574364e4ec6ec20f87e',
    privateKey: '0xc3185aba90f5df13a1268eb85f65a723f9126d0d65013717357c2fd71fc25c40',
  },
];

const DEFAULT_ACCOUNT = ACCOUNTS[0].address;

export { ACCOUNTS, DEFAULT_ACCOUNT, NULL_ADDRESS };
